name: Deploy to Lil Robo Server

on:
  push:
    branches:
      - main  # Run when you push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Connect to Server and Pull Latest Code
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /var/www/lilroboweb/lilrobowebsite
          git pull origin main
